### ISSUE TITLE
download Moves Data crash

### ISSUE THREAD

**Issue by ahjin** [Jawbone/UPPlatform_iOS_SDK#24]
##### crash at: 
\+ (void)getMovesFromStartDate:(NSDate *)startDate toEndDate:(NSDate *)endDate completion:(UPBaseEventAPIArrayCompletion)completion  
{    
..........  
NSArray *jsonItems = response.data[@"items"];    <----- crash here  
..........  
}  

##### console log: 
[__NSCFArray objectForKey:]: unrecognized selector sent to instance 0x17f6f2f0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFArray objectForKey:]: unrecognized selector sent to instance 0x17f6f2f0'

**Comment by andrew-marin** [comment]
This should no longer be an issue. Likely the server was returning an array instead of a dictionary. Re-open if this persists.
