### ISSUE TITLE
Mood enum 'Good' seems to be wrong value

### ISSUE THREAD

**Issue by schmatz** [Jawbone/UPPlatform_iOS_SDK#25]
NOTE: I'm using Swift.
We ran into an issue where the value of the "Good" mood seems to be off. The page [here](https://jawbone.com/up/developer/endpoints/mood) states that it should be 8. Rather, it registers as 0 when I use the `.toRaw()` function on it.

**Comment by andrew-marin** [comment]
Try using 'rawValue' instead. toRaw and fromRaw have been replaced with rawValue as of Xcode 6.1 Beta.
