### ISSUE TITLE
No internet connection crash

### ISSUE THREAD

**Issue by ghost-code** [Jawbone/UPPlatform_iOS_SDK#31]
UPPlatform.m line 450

Method:
`- (void)sendRequest:(UPURLRequest *)request completion:(UPPlatformRequestCompletion)completion`

Line:
`NSDictionary *jsonResponse = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];`

If there is no internet connection (airplane mode), data will be nil when it gets to this point. The app will crash.

**Comment by andrew-marin** [comment]
resolved w/ #27
