### ISSUE TITLE
How to get refresh token?

### ISSUE THREAD

**Issue by davidchristiandy** [Jawbone/UPPlatform_iOS_SDK#33]
I can't seem to find the `refreshToken` property anywhere. In the success handler of `startSessionWithClientID:` I can only grab the `authenticationToken` and the `UPUser` object from `UPSession`. Do I need to make separate GET request for the refresh token (as specified in [Jawbone api docs](https://jawbone.com/up/developer/endpoints/refreshtoken))?

Thanks!

**Comment by andrew-marin** [comment]
The refresh token is stored in the Keychain and is not generally accessible. Also, that token does not get generated until the UPAuthViewController calls its 'didCompleteWithAuthCode:' delegate method, which then kicks off an Auth request. What requirements cause you to need the refresh token?

If you need to update your tokens, you can call 'refreshAccessTokenWithClientID:clientSecret:completion:' which will update your auth and refresh tokens. If you need to ensure that your session is still valid call 'validateSessionWithCompletion:' and if the UPSession in the completion is != nil, the session is still valid.

**Comment by davidchristiandy** [comment]
If I'm not mistaken, access tokens are expired after one year but it's possible to automatically renew the expiry date by hitting https://jawbone.com/auth/oauth2/token with parameter: `client_id`, `client_secret`, `grant_type=refresh_token`, `refresh_token`. I was thinking of letting the web server handle the update, so I need to send the refresh token to my web server.

Right, so the right way is to just call `refreshAccessTokenWithClientID:clientSecret:completion:` instead from the SDK. Thanks.
