### ISSUE TITLE
UPPlatformSDK.h is missing, is it intended?

### ISSUE THREAD

**Issue by davidchristiandy** [Jawbone/UPPlatform_iOS_SDK#34]
I noticed that the `UPPlatformSDK/UPPlatformSDK.h` which imports all of the header files is now missing as in the latest version. This requires explicit imports, i.e.:
```
#import <UPPlatform/UPPlatform.h>
#import <UPPlatform/UPSession.h>
#import <UPPlatform/UPUserAPI.h>
```
At first, I tried including only `UPPlatform.h`, but Xcode generates warning when I tried to access properties from `UPSession` or `UPUser`, because they are forward-declared in `UPPlatform`. 

Am I including the wrong `UPPlatform.framework` file?

Thanks!

**Comment by andrew-marin** [comment]
"UP.h" should contain the imports you are looking for.

**Comment by davidchristiandy** [comment]
Thanks!
