### ISSUE TITLE
Cannot start session if redirect URL is HTTPS

### ISSUE THREAD

**Issue by davidchristiandy** [Jawbone/UPPlatform_iOS_SDK#35]
I have two app currently present on Jawbone. One app uses HTTP as the redirect URL (and works fine). The other one, has an HTTPS redirect URL. Every time I call `startSessionWithClientID`,  the Jawbone login screen slides up from bottom and then instantly slides back down. No errors, nothing.

Then, I tried to change the redirect URL to non-HTTPS. Apparently, it doesn't immediately close like before, but since the redirect URL is different with the one that's registered, it displays an error "invalid redirect".

```objc
#import <UPPlatform/UPPlatform.h>
#import <UPPlatform/UPSession.h>
#import <UPPlatform/UPUserAPI.h>

... some code ...
 
[[UPPlatform sharedPlatform] startSessionWithClientID:JAWBONE_CLIENT_ID 
                                         clientSecret:JAWBONE_CLIENT_SECRET
                                            authScope:UPPlatformAuthScopeBasicRead 
                                          redirectURI:JAWBONE_REDIRECT_URL 
                                           completion:^(UPSession *session, NSError *error)
{
    NSLog(@"%@ with %@ and error: %@", session, session.currentUser, error.description);
    if(session) {
        // some code that never got executed..
    }
}];
```

The NSLog is printed to console with the following output: 
`UPSession: { authenticationToken: (null) } with (null) and error: (null)`

..So it actually enters the completion block but strangely it assumes that the session is present, even if it's a brand new device or a new/reset simulator.

**Comment by brynbodayle** [comment]
I'm experiencing this issue as well.

In `UPAuthViewController.m` there is this block of code which is causing this behavior:

```
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType
{
    if ([request.URL.scheme isEqualToString:self.redirectURIScheme])
    {
        NSString *query = request.URL.query;
        NSString *code = [query stringByReplacingOccurrencesOfString:@"code=" withString:@""];
        
        [self hideWithCompletion:nil];
        [self.delegate authViewController:self didCompleteWithAuthCode:code];
        
        return NO;
    }
    
    return YES;
}
```

Not sure what the goal was here. Especially since the developer site is requiring that you use https.
![screen shot 2015-04-30 at 9 47 01 am](https://cloud.githubusercontent.com/assets/1455522/7415366/f124566e-ef1d-11e4-896a-3f787176a372.png)

**Comment by doonware** [comment]
Its been a while but is this issue still valid?

**Comment by dvdchr** [comment]
Sorry, haven't got the chance to test this again using latest version. Probably someone will raise this again if this still happens.
