### ISSUE TITLE
Got "You must be logged in to perform that action" after login for only a few hours.

### ISSUE THREAD

**Issue by hlung** [Jawbone/UPPlatform_iOS_SDK#36]
I use `-startSessionWithClientID` to login to Jawbone and everything went well. `-validateSessionWithCompletion` on subsequent app launches returns the session correctly. But after closing the app for a couple hours and launch up again, now `-validateSessionWithCompletion` gives me an error, like the session token is no longer valid for some reason. I think the token is suppose to work for about 1 year. So a few hours seems to be too little to be useful. I don't know what cause this.

The validate code:
```
    [[UPPlatform sharedPlatform] validateSessionWithCompletion:^(UPSession *session, NSError *error) {
        self.isAuthorized = (session != nil);
        if (error) {
            NSLog(@"error: %@", error);
        }
        BLOCK_SAFE_RUN_MAINTHREAD(completion, self.isAuthorized, error);
    }];
```

The error it print out:
```
Error Domain=com.jawbone.up Code=401 "You must be logged in to perform that action" UserInfo=0x7fafb3db7150 {NSLocalizedDescription=You must be logged in to perform that action}
```

Subsequent validateSessionWithCompletion calls will return this error, indicating currentSession was already cleared by the SDK:
```
Error Domain=com.jawbone.up Code=0 "No current session" UserInfo=0x7f95d274c9e0 {NSLocalizedDescription=No current session}
```

**Comment by hlung** [comment]
...

**Comment by andrew-marin** [comment]
When a 401 response is received from the server, the current session is cleared since authorization cannot be determine. Thus when you call -validateSessionWithCompletion: you get the "No current session" message.

Are you calling -startSessionWithClientID: on subsequent launches after the app has been terminated (in order to authenticate)? If so, do you get any error output from that method?

You may also need to call -refreshAccessTokenWithClientID: in case the access token was somehow compromised. Check out https://jawbone.com/up/developer/authentication for more detailed info on the Authorization flow.

**Comment by hlung** [comment]
No, I only call `-startSessionWithClientID:` just once when authenticating Jawbone user. It seems like the token just go invalid after idle for a few hours. I can do `-refreshAccessTokenWithClientID:` every time the token is invalid, but that still doesn't look like a good solution to me. I wonder what can potentially be the source of this token compromising.

**Comment by hlung** [comment]
We actually have a web service, which uses the same jawbone client id / app secret to retrieve a token for fetching data from Jawbone after receiving webhooks from Jawbone. Would this be a cause?

**Comment by andrew-marin** [comment]
Could be. If your server is requesting another access token using the same credentials, the token referenced in your app would become invalid.

**Comment by hlung** [comment]
Yeah, I remove my Jawbone credentials on the server side and didn't have an issue on the app anymore.

But, in case if the user has my same app installed on multiple devices and old token goes invalid each time user signs in on a new device. What should I do in this case, refresh the token all the time?
