### ISSUE TITLE
Error getting user's friends

### ISSUE THREAD

**Issue by bryamrr** [Jawbone/UPPlatform_iOS_SDK#37]
Hi,  I'm using UPPlatform iOS SDK with Swift and I having this runtime error when trying to get user's friends. Do you know what's happening?

![image](https://cloud.githubusercontent.com/assets/7347327/11411331/291c9828-939d-11e5-8511-08337f708a3b.png)

**Comment by bryamrr** [comment]
The first line says [__NSCFDictionary stringForKey:]: unrecognized selector sent to instance 0x78643110

Can anybody help me with this, please.

**Comment by andrew-marin** [comment]
stringForKey: is not a method on NSDictionary, thus you get the crash. You likely want to use objectForKey: instead.
