### ISSUE TITLE
How to get Refresh token, token expire date, refresh token expire date?

### ISSUE THREAD

**Issue by sauvikatinnofied** [Jawbone/UPPlatform_iOS_SDK#39]
Hi,

In my current application, I need to authenticate my application from Jawbone Up. So I am calling 

```swift
UPPlatform.sharedPlatform().startSessionWithClientID("clientID", clientSecret: "ClientSecret", authScope: .BasicRead,
 redirectURI: "http://mysite.com", presentingViewController: self) { (session: UPSession?, error: NSError?) -> Void in
}
```

In the block, I am receiving only *authentication token* from `session.authenticationToken`. But I need 

**refresh token, token expire date, refresh token expire date** as well. How can I get them?

**Comment by andrew-marin** [comment]
The [Jawbone Developer Portal - Authentication](https://jawbone.com/up/developer/authentication) page has lots of valuable information if you have not read it before.

Generally the auth/access token will expire 1 year from generation. The refresh token is stored automatically for you in the UPPlatform keychain (along with the access token). Should you need to refresh your access token, call `refreshAccessTokenWithClientID:` with your client ID and secret, and the SDK will use the refresh token stored.

We do not expose expiration dates. If you need to explicitly acquire the refresh token, you can retrieve it via the refresh token endpoint as described [here.](https://jawbone.com/up/developer/endpoints/refreshtoken)
