### ISSUE TITLE
startSessionWithClientID fails with "Unable to decode: "

### ISSUE THREAD

**Issue by cz4rny** [Jawbone/UPPlatform_iOS_SDK#40]
When I'm calling the startSessionWithClientID providing correct client id, secret, auth scope and redirect URI I receive an error:

`Error Domain=com.jawbone.up Code=0 "Unable to decode: " UserInfo={NSLocalizedDescription=Unable to decode: }.`

I have tried the HelloUp application and I'm able to login there successfully with the same credentials. However the HelloUp application has an [older framework](https://github.com/Jawbone/UPPlatform_iOS_SDK/tree/master/Examples/HelloUP/UPPlatformSDK.framework) file in the repository linked to it.

I'm trying both the CocoaPods version and a self built version from github, but no luck. I'm using iOS 9.2 SDK with Deployment Target being 8.0 and I'm using swift.

**Comment by andrew-marin** [comment]
Did you submit your redirect URI to [Jawbone UP Developer Portal](http://developers.jawbone.com/)? Which `startSessionWithClientID:` method are you using and do you have any additional insight into what point in the flow this error returns?

**Comment by doonware** [comment]
FYI the Framework has just been updated

**Comment by cz4rny** [comment]
@andrew-marin I'm using the correct redirrectURI. I can confirm that, because if a wrong URI is used, then an explicit error on the login screen is displayed. Also the same data is used in the Android app using Jawbone SDK.

``` swift
            UPPlatform.sharedPlatform().startSessionWithClientID(JawboneService.CLIENT_ID,
                    clientSecret: JawboneService.CLIENT_SECRET,
                    authScope: JawboneService.AUTH_SCOPE,
                    redirectURI: JawboneService.REDIRECT_URI,
                    completion: {
                        session, error in
                        if error != nil || session == nil {
                            DDLogError("Error authenticating Jawbone: \(error).")
                            return
                        }

                        DDLogInfo("Authenticated with Jawbone and session: \(session).")
                    })
```

Let me try the never version you're referring. However there's no new version on cocoapods, right?

EDIT: Oh, and the point at which I'm getting this error is after successfully logging in and granting access to my app to the data. So through the modal login screen I'm being moved to the grant access screen and on accepting the settings the code above brings the error described originally.

**Comment by cz4rny** [comment]
@andrew-marin I've just downloaded the latest code from repo and used the new framework. Unfortunately I'm receiving the [same error as before](https://github.com/Jawbone/UPPlatform_iOS_SDK/issues/40#issue-135733546).

I made sure that I'm using the latest framework by cleaning the project and removing DerrivedData. By inspecting the latest commit to this repository I see, that nothing network/parsing related has been touched.

**Comment by doonware** [comment]
Looks like the error is occurring in `- (void)authViewController:(UPAuthViewController *)viewController didCompleteWithAuthCode:(NSString *)code` delegate callback.

Sadly for this there isn't much to go on, as the error we are receiving from the server is "unable to be decoded" (so we can't get more granularity at this point). I wonder if it has to do with the authScope you are specifying? Try to authorize a single scope and see what happens.

I will create a sample project later today to see if I can repro your issue.

**Comment by cz4rny** [comment]
@andrew-marin yeah man I've tried getting more information by putting the traffic through Charles proxy. Unfortunately the SDKs HTTPS code wouldn't budge and was always unhappy with the SSL proxy. Other apps and my network code cleanly accepts the Charles fake SSL certificate so I can clearly sniff the traffic, but the requests made by your SDK break at the handshake phase.

My auth scope:

``` swift
    static let AUTH_SCOPE: UPPlatformAuthScope = UPPlatformAuthScope(rawValue: UPPlatformAuthScope.WeightRead.rawValue
            | UPPlatformAuthScope.WeightWrite.rawValue
            | UPPlatformAuthScope.MoveRead.rawValue
            | UPPlatformAuthScope.MoveWrite.rawValue
            | UPPlatformAuthScope.BasicRead.rawValue
            | UPPlatformAuthScope.ExtendedRead.rawValue
```

I'll try to make a simplistic scope tomorrow (it's 22:19 here) with one simple read or something like that.

Thanks for actually investigating even though you've got so little to go on.

**Comment by cz4rny** [comment]
@andrew-marin Dear Andrew. I've managed to sniff the SSL traffic to Jawbone. Please find attached a Charles [jawbone.txt](https://github.com/Jawbone/UPPlatform_iOS_SDK/files/147839/jawbone.txt) file with each request and responses. I had to change the extension to txt to get it to Github, but you can rename it to XML and open that XML in any editor and you can get all the headers, queries, cookies and everything that happened. Hope this is everything needed to get to the bottom of this.

I've also changed the `authScope` to `UPPlatformAuthScope.All`:

``` swift
            UPPlatform.sharedPlatform().startSessionWithClientID(JawboneService.CLIENT_ID,
                    clientSecret: JawboneService.CLIENT_SECRET,
                    authScope: UPPlatformAuthScope.All,
                    redirectURI: "http://localhost/myacticol?",
                    completion: {
                        session, error in
                        if error != nil || session == nil {
                            DDLogError("Error authenticating Jawbone: \(error).")
                            reject(error)
                            return
                        }

                        DDLogInfo("Authenticated with Jawbone and session: \(session).")
                        fulfill()
                    })
        }
    }
```

**Comment by cz4rny** [comment]
@andrew-marin Did the network trace help out getting to the bottom of this?

**Comment by doonware** [comment]
Network trace is great. Should definitely provide more context into the problem. Haven't been able to dive into it yet, but I will find some time today/tonight to parse through it and see if there are any red flags.

**Comment by cz4rny** [comment]
@andrew-marin Thanks for getting back to me. Great news! The project I'm using it for slowly heads till closing so I'm pressured to push this even through official Jawbone developer portal or something. But thanks to your message I'm holding off and keeping my fingers crossed.

**Comment by doonware** [comment]
Just started to look into this while at lunch, and it appears to fail during the redirect step. The auth token seems to be successfully generated however (which is good). 

One thing I noticed with the code posted above, is that there is an ampersand at the end of the redirect URI. I have a feeling that may be causing the redirect to fail. Was this a typo or is it intentional? I would suggest to try removing that from the redirect URI (in your app and developer portal) and see if anything changes.

Sent a note to Platform team, and am waiting to hear back from them to see if they have any additional context around this issue. FYI we are heads down over here however, so it may not happen in a timely enough matter before your submission.

**Comment by cz4rny** [comment]
@andrew-marin You mean the question mark at the end of the redirection URL `redirectURI: "http://localhost/myacticol?"`? It's there intentionally and I've double checked right now without it. When I remove the question mark I get the `**Error code:** invalid_redirect` message.

Let me ask if I could change the redirect URL on the panel. I'm afraid to blindly change it in the panel, as there's already an Android application on the PlayStore which would start failing when the URL is changed. But it's worth a try if only for a few minutes.

**Comment by cz4rny** [comment]
@andrew-marin I've removed the question mark in the Jawbone panel and not only the Android application hasn't stop working, but I'm getting a bit further with the Jawbone SDK. This is great news! Let me dig more into it, maybe it's a breakthrough?

**Comment by doonware** [comment]
D'oh, yes I mean the question mark :P. Glad to hear you are making progress! If you get stuck again let us know.
