### ISSUE TITLE
Authentication does not work from Modal

### ISSUE THREAD

**Issue by chrisfoulds** [Jawbone/UPPlatform_iOS_SDK#44]
Trying to launch authentication from a modal that has been launched from a tabcontroller.

This does not work due to this code not detecting different launch methods in UPAuthViewController.m
- (void)show
  {
  [self.rootViewController presentViewController:self animated:YES completion:^{
      [self.webView loadRequest:[NSURLRequest requestWithURL:self.authURL]];
  }];
  }

Warning: Attempt to present <UPAuthViewController: 0x7f9316989000> on <UITabBarController: 0x7f93153cb660> whose view is not in the window hierarchy!

**Comment by xinsight** [comment]
Are you using the latest version? `show` has been replaced with `- (void)presentWithViewController:(UIViewController *)presentingViewController;`

**Comment by doonware** [comment]
+1 xinsights
